# Generated by Django 3.1.3 on 2020-12-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='user',
            name='face',
            field=models.CharField(blank=True, max_length=100, verbose_name='人脸'),
        ),
    ]
