# Generated by Django 3.1.3 on 2020-11-17 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0003_auto_20201117_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='face',
            field=models.ImageField(blank=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'], message='必须为jpg,png格式的文件')], verbose_name='人脸'),
        ),
    ]
