# Generated by Django 3.1.3 on 2020-11-24 09:26

from django.db import migrations, models
import face.models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0004_auto_20201117_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='face',
            field=models.ImageField(blank=True, upload_to=face.models.get_photo_path, verbose_name='人脸'),
        ),
    ]
