# Generated by Django 3.1.3 on 2020-11-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0005_auto_20201124_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=20, unique=True, verbose_name='学号'),
        ),
    ]
