# Generated by Django 3.1.3 on 2020-11-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0006_auto_20201124_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='姓名'),
        ),
    ]
